# Generated by Django 3.1.5 on 2021-02-05 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolinvite',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.pool'),
        ),
    ]
