# Generated by Django 3.1.5 on 2021-02-06 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_auto_20210206_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolinvite',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='pools.pool'),
        ),
    ]
