# Verify at http://yaml-online-parser.appspot.com/
version: "3.8"

services:

  django:
    restart: unless-stopped
    container_name: django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; echo "Waiting for Postgres" ; done; /start.sh'
    volumes:
      - .:/app
    ports:
      - "9001:25" # HOST:CONTAINER
      - 80:8000 # HOST:CONTAINER
    env_file:
      - ./.envs/.local/.django
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432 # HOST:CONTAINER
    env_file:
      - ./.envs/.local/.postgres
volumes:
  postgres_data: