# Generated by Django 3.1.5 on 2021-02-16 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='investment_transactions', to='pools.pool'),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='outgoing_investment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='billing_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccountdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bank_account_detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='balancetransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='balance_transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
