# Generated by Django 3.1.5 on 2021-02-07 18:34

import config.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210206_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='Your 12 digit Aadhaar Number (as written on your aadhaar card).', max_length=12, unique=True, validators=[config.validators.validate_aadhaar_number], verbose_name='Aadhaar Card Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.DecimalValidator, config.validators.validate_amount], verbose_name='Balance Amount'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Your 10 digit PAN Number (as written on your PAN card).', max_length=10, unique=True, validators=[config.validators.validate_pan_number], verbose_name='PAN Card Number'),
        ),
    ]
